### ISSUE TITLE
entered unreachable code at Portal<T>::wait_once

### ISSUE THREAD

**Issue by Dirbaio** [embassy-rs/nrf-softdevice#110]
I'm seeing this error in production somewhat rarely. I haven't been able to repro it yet.

```
 ERROR device            > 93281.127 panicked at 'internal error: entered unreachable code'
stack backtrace:
   0: core::panicking::panic
        at /root/.rustup/toolchains/nightly-2021-10-16-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:41
   1: __defmt_default_panic
        at /root/.cargo/git/checkouts/defmt-7f5b74b4e6ff55d4/50e3db3/defmt/src/lib.rs:367
   2: nrf_softdevice::util::portal::Portal<T>::wait_once::{{closure}}::{{closure}}
   3: nrf_softdevice::util::portal::Portal<T>::call
   4: nrf_softdevice::ble::on_evt
   5: nrf_softdevice::events::run::{{closure}}::{{closure}}
        at /root/.cargo/git/checkouts/nrf-softdevice-c6f1e1abd1ad6893/6a01c4c/nrf-softdevice/src/events.rs:73
   6: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.18/src/future/poll_fn.rs:56
   7: nrf_softdevice::events::run::{{closure}}
        at /root/.cargo/git/checkouts/nrf-softdevice-c6f1e1abd1ad6893/6a01c4c/nrf-softdevice/src/events.rs:54
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
        at /root/.rustup/toolchains/nightly-2021-10-16-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
   9: nrf_softdevice::softdevice::Softdevice::run::{{closure}}
        at /root/.cargo/git/checkouts/nrf-softdevice-c6f1e1abd1ad6893/6a01c4c/nrf-softdevice/src/softdevice.rs:323
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
        at /root/.rustup/toolchains/nightly-2021-10-16-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
  11: application::ble::softdevice_task::task::{{closure}}
        at /builds/firmware/firmware/ak-application/src/application/ble.rs:131
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
        at /root/.rustup/toolchains/nightly-2021-10-16-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
  13: embassy::executor::raw::TaskStorage<F>::poll
        at /root/.cargo/git/checkouts/embassy-00cf184034ab5a1f/7561fa1/embassy/src/executor/raw/mod.rs:183
  14: core::cell::Cell<T>::get
        at /root/.rustup/toolchains/nightly-2021-10-16-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cell.rs:436
  15: embassy::executor::raw::timer_queue::TimerQueue::update
        at /root/.cargo/git/checkouts/embassy-00cf184034ab5a1f/7561fa1/embassy/src/executor/raw/timer_queue.rs:35
  16: embassy::executor::raw::Executor::poll::{{closure}}
        at /root/.cargo/git/checkouts/embassy-00cf184034ab5a1f/7561fa1/embassy/src/executor/raw/mod.rs:329
  17: embassy::executor::raw::run_queue::RunQueue::dequeue_all
        at /root/.cargo/git/checkouts/embassy-00cf184034ab5a1f/7561fa1/embassy/src/executor/raw/run_queue.rs:71
  18: embassy::executor::raw::Executor::poll
        at /root/.cargo/git/checkouts/embassy-00cf184034ab5a1f/7561fa1/embassy/src/executor/raw/mod.rs:308
  19: cortex_m::asm::inline::__wfe
        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-0.7.3/src/../asm/inline.rs:177
  20: cortex_m::asm::wfe
        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-0.7.3/src/asm.rs:49
  21: embassy::executor::arch::Executor::run
        at /root/.cargo/git/checkouts/embassy-00cf184034ab5a1f/7561fa1/embassy/src/executor/arch/cortex_m.rs:54
  22: application::sys::__cortex_m_rt_main
  23: application::sys::__cortex_m_rt_main
        at /builds/firmware/firmware/ak-application/src/application/../sys.rs:158
error: the stack appears to be corrupted beyond this point
```

**Comment by Dirbaio** [comment]
It's hitting the `unreachable!` here:

https://github.com/embassy-rs/nrf-softdevice/blob/8a7ae35733156e903a6c9ddc8dc3c0b7dfada59c/nrf-softdevice/src/ble/l2cap.rs#L199

I've changed it to print which event it is, we'll see in a few days...
